Questionnaire.Web/Controllers/ApplicationController.cs
using System.Threading.Tasks;
using Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Orleans;
using Questionnaire.Web.Models;

namespace Questionnaire.Web.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly IClusterClient _clusterClient;

        public ApplicationController(IClusterClient clusterClient)
        {
            _clusterClient = clusterClient;
        }

        public async Task<IActionResult> Index()
        {
            var grain = _clusterClient.GetGrain<IQuestionnaireListGrain>(0);
            var appList = await grain.GetAll();
            return View(new ApplicationListModel {Applications = appList});
        }

        public async Task<IActionResult> Edit(int id)
        {
            var grain = _clusterClient.GetGrain<IQuestionnaireManagerGrain>(id);
            var snapshot = await grain.GetSnapshot();

            return View(new ApplicationModel {Id = id, Snapshot = JsonConvert.SerializeObject(snapshot)});
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ApplicationModel model)
        {
            var grain = _clusterClient.GetGrain<IQuestionnaireManagerGrain>(model.Id);
            await grain.Set(model.ControlId, model.Value);
            var snapshot = await grain.GetSnapshot();
            return View("Edit", new ApplicationModel {Id = model.Id, Snapshot = JsonConvert.SerializeObject(snapshot)});
        }
    }
}

Questionnaire.Web/Views/Application/Edit.cshtml
@model ApplicationModel
@{
    ViewData["Title"] = "Editor";
}

<div>
    <hr/>
    <input type="hidden" id="applicationId" asp-for="Id"/>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-3">
                <form asp-controller="Application" asp-action="Edit" method="post">
                    <div class="form-group">
                        <label>
                            Question:
                            <select style="width: 280px" asp-for="ControlId" asp-items="Model.Controls"></select>
                        </label>
                    </div>
                    <div class="form-group">
                        <label>
                            Value:
                            <input asp-for="Value" type="text" class="form-control">
                        </label>
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
            <div class="col-xs-9">
                <textarea id="snapshot" asp-for="Snapshot" cols="80" rows="20"></textarea>
                <button id="reload" type="submit" class="btn btn-default">Reload Snapshot</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(() => {
            var applicationId = $("#applicationId").val();
            var $snapshot = $("#snapshot");
            $("#reload").click(() => {
                $.get(`/api/questionnaire-shapshot/${applicationId}`).then(o => {
                    $snapshot.val(JSON.stringify(o));
                })

            });
        });
    </script>
}

Questionnaire.Web/Views/Application/Index.cshtml
@model ApplicationListModel
@{
    ViewData["Title"] = "Application";
}

<div>
    <hr/>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-3">
                <ul>
                    @foreach (var item in Model.Applications)
                    {
                        <li>
                            <a asp-controller="Application" asp-action="Edit" asp-route-id="@item">Application @item</a>
                        </li>
                    }
                </ul>
                <a asp-controller="Application" class="btn btn-primary" asp-action="Edit" asp-route-id="@(Model.Applications.Count == 0 ? 1 : Model.Applications.Max() + 1)">Create New</a>
                <a id="generator" class="btn btn-primary">Generate 20</a>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(() => {
            $("#generator").click(() => $.post("/api/questionnaire-generator/20"));
        });

    </script>
}